<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Ejercicio1.aspx.cs" Inherits="tp5programacion3.Ejercicio1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <p>
            <br />
             <asp:GridView ID="gvProductos" runat="server" AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="gvProductos_RowDeleting" OnRowEditing="gvProductos_RowEditing" Width="594px" OnRowCancelingEdit="gvProductos_RowCancelingEdit" OnRowUpdating="gvProductos_RowUpdating" AllowPaging="True" OnPageIndexChanging="gvProductos_PageIndexChanging">
                 <AlternatingRowStyle BackColor="White" />
                 <Columns>
                     <asp:TemplateField HeaderText="Id Producto">
                         <EditItemTemplate>
                             <asp:Label ID="lbl_eit_IdProducto" runat="server" Text='<%# Bind("Id_Producto") %>'></asp:Label>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="lbl_it_IdProducto" runat="server" Text='<%# Bind("Id_Producto") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Nombre Producto">
                         <EditItemTemplate>
                             <asp:TextBox ID="txt_eit_NombreProducto" runat="server" Text='<%# Bind("Nombre_Producto") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="lbl_it_NombreProducto" runat="server" Text='<%# Bind("Nombre_Producto") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Cantidad por Unidad">
                         <EditItemTemplate>
                             <asp:TextBox ID="txt_eit_CantidadporUnidad" runat="server" Text='<%# Bind("Cantidad_por_Unidad") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="lbl_it_CantidadporUnidad" runat="server" Text='<%# Bind("Cantidad_por_Unidad") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                     <asp:TemplateField HeaderText="Precio Unidad">
                         <EditItemTemplate>
                             <asp:TextBox ID="txt_eit_PrecioUnidad" runat="server" Text='<%# Bind("Precio_Unidad") %>'></asp:TextBox>
                         </EditItemTemplate>
                         <ItemTemplate>
                             <asp:Label ID="lbl_it_PrecioUnidad" runat="server" Text='<%# Bind("Precio_Unidad") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                 </Columns>
                 <EditRowStyle BackColor="#2461BF" />
                 <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                 <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                 <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                 <RowStyle BackColor="#EFF3FB" />
                 <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                 <SortedAscendingCellStyle BackColor="#F5F7FB" />
                 <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                 <SortedDescendingCellStyle BackColor="#E9EBEF" />
                 <SortedDescendingHeaderStyle BackColor="#4870BE" />
             </asp:GridView>
        </p>
        <div>
            <br />
        </div>
    </form>
</body>
</html>

